@TodoApi_HostAddress = https://localhost:7057

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
    "name":"Buy water",
    "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

GET {{TodoApi_HostAddress}}/todoitems/4

###

PUT {{TodoApi_HostAddress}}/todoitems/4
Content-Type: application/json

{
    "name":"Visit the dentist",
    "isComplete":false
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/4

###
